<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'general.app_name',
                'value' => 'Affiliate COD Platform',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application name',
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'general.app_description',
                'value' => 'Plateforme d\'affiliation COD pour la vente en ligne',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application description',
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'general.app_slogan',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application slogan',
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'general.app_keywords',
                'value' => 'affiliation, COD, ecommerce',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application keywords for SEO',
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'general.company_logo',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Company logo URL',
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'general.favicon',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application favicon URL',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'general.facebook_pxm_api_key',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Facebook Pixel API Key',
                'is_public' => false,
                'sort_order' => 7,
            ],
            [
                'key' => 'general.company_name',
                'value' => 'Votre Entreprise',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Company name',
                'is_public' => true,
                'sort_order' => 8,
            ],
            [
                'key' => 'general.company_email',
                'value' => 'contact@votre-entreprise.com',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Company email',
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'general.company_phone',
                'value' => '+212 6 12 34 56 78',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Company phone',
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'general.company_address',
                'value' => 'Casablanca, Maroc',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Company address',
                'is_public' => true,
                'sort_order' => 7,
            ],
            [
                'key' => 'general.default_language',
                'value' => 'fr',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Default language',
                'is_public' => true,
                'sort_order' => 8,
            ],
            [
                'key' => 'general.timezone',
                'value' => 'Africa/Casablanca',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Default timezone',
                'is_public' => false,
                'sort_order' => 9,
            ],
            [
                'key' => 'general.currency',
                'value' => 'MAD',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Default currency',
                'is_public' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'general.currency_symbol',
                'value' => 'MAD',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Currency symbol',
                'is_public' => true,
                'sort_order' => 11,
            ],
            [
                'key' => 'general.date_format',
                'value' => 'DD/MM/YYYY',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Date format',
                'is_public' => true,
                'sort_order' => 12,
            ],
            [
                'key' => 'general.time_format',
                'value' => '24',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Time format',
                'is_public' => true,
                'sort_order' => 13,
            ],
            [
                'key' => 'general.number_format',
                'value' => 'european',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Number format',
                'is_public' => true,
                'sort_order' => 14,
            ],
            [
                'key' => 'general.maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'general',
                'description' => 'Maintenance mode',
                'is_public' => true,
                'sort_order' => 15,
            ],

            // Branding & Appearance Settings
            [
                'key' => 'general.app_logo',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application logo URL',
                'is_public' => true,
                'sort_order' => 16,
            ],
            [
                'key' => 'general.app_favicon',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application favicon URL',
                'is_public' => true,
                'sort_order' => 17,
            ],
            [
                'key' => 'general.primary_color',
                'value' => '#6366F1',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Primary brand color',
                'is_public' => true,
                'sort_order' => 18,
            ],
            [
                'key' => 'general.secondary_color',
                'value' => '#8B5CF6',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Secondary brand color',
                'is_public' => true,
                'sort_order' => 19,
            ],
            [
                'key' => 'general.login_background_image',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Login page background image URL',
                'is_public' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'general.signup_background_image',
                'value' => '',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Signup page background image URL',
                'is_public' => true,
                'sort_order' => 21,
            ],
            [
                'key' => 'general.app_theme',
                'value' => 'light',
                'type' => 'string',
                'category' => 'general',
                'description' => 'Application theme (light/dark/auto)',
                'is_public' => true,
                'sort_order' => 22,
            ],

            // Business Settings
            [
                'key' => 'business.default_commission_rate',
                'value' => '10',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Default commission rate (%)',
                'is_public' => false,
                'sort_order' => 1,
            ],
            [
                'key' => 'business.min_commission_threshold',
                'value' => '50',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Minimum commission threshold',
                'is_public' => false,
                'sort_order' => 2,
            ],
            [
                'key' => 'business.commission_calculation_method',
                'value' => 'per_order',
                'type' => 'string',
                'category' => 'business',
                'description' => 'Commission calculation method',
                'is_public' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'business.tiered_commissions_enabled',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'business',
                'description' => 'Tiered commissions enabled',
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'business.tier_1_rate',
                'value' => '8',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 1 commission rate (%)',
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'business.tier_1_threshold',
                'value' => '1000',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 1 sales threshold',
                'is_public' => false,
                'sort_order' => 6,
            ],
            [
                'key' => 'business.tier_2_rate',
                'value' => '12',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 2 commission rate (%)',
                'is_public' => false,
                'sort_order' => 7,
            ],
            [
                'key' => 'business.tier_2_threshold',
                'value' => '5000',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 2 sales threshold',
                'is_public' => false,
                'sort_order' => 8,
            ],
            [
                'key' => 'business.tier_3_rate',
                'value' => '15',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 3 commission rate (%)',
                'is_public' => false,
                'sort_order' => 9,
            ],
            [
                'key' => 'business.tier_3_threshold',
                'value' => '10000',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tier 3 sales threshold',
                'is_public' => false,
                'sort_order' => 10,
            ],
            [
                'key' => 'business.auto_confirm_timeout',
                'value' => '24',
                'type' => 'integer',
                'category' => 'business',
                'description' => 'Auto confirmation timeout (hours)',
                'is_public' => false,
                'sort_order' => 11,
            ],
            [
                'key' => 'business.order_number_prefix',
                'value' => 'ORD',
                'type' => 'string',
                'category' => 'business',
                'description' => 'Order number prefix',
                'is_public' => false,
                'sort_order' => 12,
            ],
            [
                'key' => 'business.order_number_format',
                'value' => 'YYYYMMDD-####',
                'type' => 'string',
                'category' => 'business',
                'description' => 'Order number format',
                'is_public' => false,
                'sort_order' => 13,
            ],
            [
                'key' => 'business.return_window_days',
                'value' => '7',
                'type' => 'integer',
                'category' => 'business',
                'description' => 'Return window (days)',
                'is_public' => false,
                'sort_order' => 14,
            ],
            [
                'key' => 'business.refund_processing_days',
                'value' => '3',
                'type' => 'integer',
                'category' => 'business',
                'description' => 'Refund processing time (days)',
                'is_public' => false,
                'sort_order' => 15,
            ],
            [
                'key' => 'business.min_withdrawal_amount',
                'value' => '100',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Minimum withdrawal amount',
                'is_public' => false,
                'sort_order' => 16,
            ],
            [
                'key' => 'business.max_withdrawal_amount',
                'value' => '10000',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Maximum withdrawal amount',
                'is_public' => false,
                'sort_order' => 17,
            ],
            [
                'key' => 'business.withdrawal_fee_percentage',
                'value' => '2',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Withdrawal fee percentage',
                'is_public' => false,
                'sort_order' => 18,
            ],
            [
                'key' => 'business.withdrawal_fee_fixed',
                'value' => '5',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Fixed withdrawal fee',
                'is_public' => false,
                'sort_order' => 19,
            ],
            [
                'key' => 'business.withdrawal_processing_days',
                'value' => '3',
                'type' => 'integer',
                'category' => 'business',
                'description' => 'Withdrawal processing time (days)',
                'is_public' => false,
                'sort_order' => 20,
            ],
            [
                'key' => 'business.tax_rate',
                'value' => '20',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Tax rate (%)',
                'is_public' => false,
                'sort_order' => 21,
            ],
            [
                'key' => 'business.tax_included_in_prices',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'business',
                'description' => 'Tax included in prices',
                'is_public' => false,
                'sort_order' => 22,
            ],
            [
                'key' => 'business.payment_delay_days',
                'value' => '30',
                'type' => 'integer',
                'category' => 'business',
                'description' => 'Payment delay (days)',
                'is_public' => false,
                'sort_order' => 23,
            ],
            [
                'key' => 'business.auto_payout_enabled',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'business',
                'description' => 'Automatic payouts enabled',
                'is_public' => false,
                'sort_order' => 24,
            ],
            [
                'key' => 'business.auto_payout_threshold',
                'value' => '500',
                'type' => 'float',
                'category' => 'business',
                'description' => 'Automatic payout threshold',
                'is_public' => false,
                'sort_order' => 25,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('Settings seeded successfully!');
    }
}
