/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-affiliate-tiers': RouteRecordInfo<'admin-affiliate-tiers', '/admin/affiliate-tiers', Record<never, never>, Record<never, never>>,
    'admin-affiliates': RouteRecordInfo<'admin-affiliates', '/admin/affiliates', Record<never, never>, Record<never, never>>,
    'admin-affiliates-id': RouteRecordInfo<'admin-affiliates-id', '/admin/affiliates/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-boutiques': RouteRecordInfo<'admin-boutiques', '/admin/boutiques', Record<never, never>, Record<never, never>>,
    'admin-boutiques-create': RouteRecordInfo<'admin-boutiques-create', '/admin/boutiques/create', Record<never, never>, Record<never, never>>,
    'admin-categories': RouteRecordInfo<'admin-categories', '/admin/categories', Record<never, never>, Record<never, never>>,
    'admin-commissions': RouteRecordInfo<'admin-commissions', '/admin/commissions', Record<never, never>, Record<never, never>>,
    'admin-commissions-id': RouteRecordInfo<'admin-commissions-id', '/admin/commissions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-dashboard-simple': RouteRecordInfo<'admin-dashboard-simple', '/admin/dashboard-simple', Record<never, never>, Record<never, never>>,
    'admin-debug-ozonexpress': RouteRecordInfo<'admin-debug-ozonexpress', '/admin/debug/ozonexpress', Record<never, never>, Record<never, never>>,
    'admin-integrations-ozon-cities': RouteRecordInfo<'admin-integrations-ozon-cities', '/admin/integrations/ozon/cities', Record<never, never>, Record<never, never>>,
    'admin-integrations-ozon-credentials': RouteRecordInfo<'admin-integrations-ozon-credentials', '/admin/integrations/ozon/credentials', Record<never, never>, Record<never, never>>,
    'admin-kyc-documents': RouteRecordInfo<'admin-kyc-documents', '/admin/kyc-documents', Record<never, never>, Record<never, never>>,
    'admin-order-conflicts': RouteRecordInfo<'admin-order-conflicts', '/admin/order-conflicts', Record<never, never>, Record<never, never>>,
    'admin-orders-pre': RouteRecordInfo<'admin-orders-pre', '/admin/orders/pre', Record<never, never>, Record<never, never>>,
    'admin-orders-pre-id': RouteRecordInfo<'admin-orders-pre-id', '/admin/orders/pre/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-orders-shipping': RouteRecordInfo<'admin-orders-shipping', '/admin/orders/shipping', Record<never, never>, Record<never, never>>,
    'admin-orders-shipping-id': RouteRecordInfo<'admin-orders-shipping-id', '/admin/orders/shipping/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-payments': RouteRecordInfo<'admin-payments', '/admin/payments', Record<never, never>, Record<never, never>>,
    'admin-products': RouteRecordInfo<'admin-products', '/admin/products', Record<never, never>, Record<never, never>>,
    'admin-produits': RouteRecordInfo<'admin-produits', '/admin/produits', Record<never, never>, Record<never, never>>,
    'admin-produits-id': RouteRecordInfo<'admin-produits-id', '/admin/produits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-produits-id-edit': RouteRecordInfo<'admin-produits-id-edit', '/admin/produits/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-produits-create': RouteRecordInfo<'admin-produits-create', '/admin/produits/Create', Record<never, never>, Record<never, never>>,
    'admin-referrals-dashboard': RouteRecordInfo<'admin-referrals-dashboard', '/admin/referrals/dashboard', Record<never, never>, Record<never, never>>,
    'admin-referrals-dispensations': RouteRecordInfo<'admin-referrals-dispensations', '/admin/referrals/dispensations', Record<never, never>, Record<never, never>>,
    'admin-referrals-dispensations-id': RouteRecordInfo<'admin-referrals-dispensations-id', '/admin/referrals/dispensations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-referrals-referred-users': RouteRecordInfo<'admin-referrals-referred-users', '/admin/referrals/referred-users', Record<never, never>, Record<never, never>>,
    'admin-referrals-referred-users-id': RouteRecordInfo<'admin-referrals-referred-users-id', '/admin/referrals/referred-users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-reports-affiliates': RouteRecordInfo<'admin-reports-affiliates', '/admin/reports-affiliates', Record<never, never>, Record<never, never>>,
    'admin-reports-sales': RouteRecordInfo<'admin-reports-sales', '/admin/reports-sales', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-stock': RouteRecordInfo<'admin-stock', '/admin/stock', Record<never, never>, Record<never, never>>,
    'admin-support-tickets': RouteRecordInfo<'admin-support-tickets', '/admin/support/tickets', Record<never, never>, Record<never, never>>,
    'admin-support-tickets-id': RouteRecordInfo<'admin-support-tickets-id', '/admin/support/tickets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-support-tickets-create': RouteRecordInfo<'admin-support-tickets-create', '/admin/support/tickets/create', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-variants-attributs': RouteRecordInfo<'admin-variants-attributs', '/admin/variants/attributs', Record<never, never>, Record<never, never>>,
    'admin-variants-attributs-id-valeurs': RouteRecordInfo<'admin-variants-attributs-id-valeurs', '/admin/variants/attributs/:id/valeurs', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-withdrawals': RouteRecordInfo<'admin-withdrawals', '/admin/withdrawals', Record<never, never>, Record<never, never>>,
    'admin-withdrawals-id': RouteRecordInfo<'admin-withdrawals-id', '/admin/withdrawals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-withdrawals-create': RouteRecordInfo<'admin-withdrawals-create', '/admin/withdrawals/create', Record<never, never>, Record<never, never>>,
    'affiliate-catalogue': RouteRecordInfo<'affiliate-catalogue', '/affiliate/catalogue', Record<never, never>, Record<never, never>>,
    'affiliate-catalogue-index-old': RouteRecordInfo<'affiliate-catalogue-index-old', '/affiliate/catalogue/index__old', Record<never, never>, Record<never, never>>,
    'affiliate-commissions': RouteRecordInfo<'affiliate-commissions', '/affiliate/commissions', Record<never, never>, Record<never, never>>,
    'affiliate-dashboard': RouteRecordInfo<'affiliate-dashboard', '/affiliate/dashboard', Record<never, never>, Record<never, never>>,
    'affiliate-marketing': RouteRecordInfo<'affiliate-marketing', '/affiliate/marketing', Record<never, never>, Record<never, never>>,
    'affiliate-orders': RouteRecordInfo<'affiliate-orders', '/affiliate/orders', Record<never, never>, Record<never, never>>,
    'affiliate-orders-id': RouteRecordInfo<'affiliate-orders-id', '/affiliate/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'affiliate-payments': RouteRecordInfo<'affiliate-payments', '/affiliate/payments', Record<never, never>, Record<never, never>>,
    'affiliate-referrals': RouteRecordInfo<'affiliate-referrals', '/affiliate/referrals', Record<never, never>, Record<never, never>>,
    'affiliate-referrals-rewards': RouteRecordInfo<'affiliate-referrals-rewards', '/affiliate/referrals/rewards', Record<never, never>, Record<never, never>>,
    'affiliate-referrals-users': RouteRecordInfo<'affiliate-referrals-users', '/affiliate/referrals/users', Record<never, never>, Record<never, never>>,
    'affiliate-tickets': RouteRecordInfo<'affiliate-tickets', '/affiliate/tickets', Record<never, never>, Record<never, never>>,
    'affiliate-tickets-id': RouteRecordInfo<'affiliate-tickets-id', '/affiliate/tickets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'affiliate-signup': RouteRecordInfo<'affiliate-signup', '/affiliate-signup', Record<never, never>, Record<never, never>>,
    'affiliate-verified': RouteRecordInfo<'affiliate-verified', '/affiliate-verified', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'pslug': RouteRecordInfo<'pslug', '/p/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'test-auth': RouteRecordInfo<'test-auth', '/test-auth', Record<never, never>, Record<never, never>>,
    'unauthorized': RouteRecordInfo<'unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
  }
}
